import type { Dispatch } from 'react'
import type { Action, State } from '../../app/state'
import { Button, Choice, SourceLink } from '../../components/Primitives'
import { scenarios } from '../../domain/scenarios'
import { ArrowLeft, BookOpen, CircleHelp, Mail, Monitor } from 'lucide-react'

export function Start({ state, dispatch }: { state: State; dispatch: Dispatch<Action> }) {
  if (state.mode === 'example') return <section className="narrow-step app-card"><span className="icon-tile lavender"><BookOpen size={24} aria-hidden="true" /></span><p className="section-label">A MADE-UP STORY TO PRACTISE WITH</p><h1 id="step-heading" tabIndex={-1}>{scenarios[state.scenario].title}</h1><p className="step-description">{scenarios[state.scenario].description}</p><p className="small-print">We’ll supply the example answers. You can change them to see how the summary changes. None of the details come from your accounts.</p><Button arrow onClick={() => dispatch({ type: 'STEP', value: 'review' })}>Continue the example</Button></section>
  if (state.startPhase === 'topic') return <section className="narrow-step app-card"><p className="section-label">LET’S PICK A STARTING POINT</p><h1 id="step-heading" tabIndex={-1}>What would you like help with?</h1><p className="step-description">Choose what sounds familiar. You don’t need to explain your relationship.</p>{state.concern && <div className="concern-reference"><strong>Your note</strong><p>{state.concern}</p><span>For your reference. This isn’t evidence of what is in your accounts.</span></div>}<p className="scope-note">This prototype covers Google device sessions and recovery connections: devices signed in to an account, and emails that can help recover another account. Other providers, location sharing and finances aren’t covered. You can also <SourceLink id="safety">read general support information (US)</SourceLink>.</p><div className="topic-choices">{([{ name: 'Shared device', label: 'We used to share a device', icon: Monitor, description: 'Review a shared tablet, one sign-in at a time.' }, { name: 'Recovery details', label: 'Our email accounts might be linked', icon: Mail, description: 'One email might help get back into another account.' }, { name: 'Not sure', label: 'I’m not sure where to start', icon: CircleHelp, description: 'Explain the basics and guide me through.' }] as const).map(topic => <button className="topic-choice" key={topic.name} onClick={() => dispatch({ type: 'TOPIC', value: topic.name })}><topic.icon size={24} aria-hidden="true" /><span><strong>{topic.label}</strong><small>{topic.description}</small></span><span aria-hidden="true">→</span></button>)}</div><p className="small-print">Your answers stay in this tab. Refreshing clears them.</p></section>
  return <section className="narrow-step app-card"><p className="section-label">BEFORE WE START · YOU CAN SKIP THIS</p><h1 id="step-heading" tabIndex={-1}>Could changing a setting cause a problem for you?</h1><p className="step-description">Someone else might notice a change to an account. Here, you can just learn what’s connected. You don’t have to change anything.</p><div className="choices">{([{ value: 'possibly', label: 'Possibly', description: 'I’d like to understand things before deciding what to do.' }, { value: 'unsure', label: 'I’m not sure', description: 'Let’s take it one step at a time.' }, { value: 'continue', label: 'I want to continue reviewing', description: 'I’m ready to look at the questions.' }] as const).map(option => <Choice selected={state.safety === option.value} key={option.value} onClick={() => dispatch({ type: 'SAFETY', value: option.value })} description={option.description}>{option.label}</Choice>)}</div><div className="step-actions"><button className="text-button" onClick={() => dispatch({ type: 'START_PHASE', value: 'topic' })}><ArrowLeft size={16} aria-hidden="true" />Back</button><button className="text-button" onClick={() => dispatch({ type: 'SAFETY', value: 'skipped' })}>Skip and continue →</button></div><div className="support-note"><p>If you think someone can monitor this device, consider reading support information on a device you trust.</p><SourceLink id="safety">Read NNEDV’s safety information (US)</SourceLink></div></section>
}
