import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import fs from 'node:fs'
const nav = (page: Page, name: string | RegExp) => page.getByRole('navigation', { name: 'Plan navigation' }).getByRole('button', { name })
async function start(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start with my own situation' }).click()
  await page.getByRole('button', { name: 'Who can get into my accounts?', exact: true }).click()
  await page.getByRole('button', { name: /Google, Gmail or Google Photos/ }).click()
  await page.getByRole('button', { name: 'Show my first step' }).click()
  await expect(page.getByRole('heading', { name: 'Keep a way back into your account', exact: true })).toBeFocused()
}

test('beginner reaches a first instruction directly; Home, Back, language and help preserve a draft', async ({ page }) => {
  await start(page)
  await expect(page.getByText('Instruction 1 of 2')).toBeVisible()
  await page.getByRole('button', { name: /My update/ }).click()
  await page.getByRole('button', { name: 'I’m not sure what I found' }).click()
  await page.getByLabel('A reminder for yourself').fill('Fictional unfinished note: ąęł')
  await page.getByRole('button', { name: 'Untangle home', exact: true }).click()
  await page.goBack()
  await expect(page.getByLabel('A reminder for yourself')).toHaveValue('Fictional unfinished note: ąęł')
  await page.getByRole('button', { name: 'Polski', exact: true }).click()
  await expect(page.getByLabel('Przypomnienie dla siebie')).toHaveValue('Fictional unfinished note: ąęł')
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByRole('button', { name: 'Help & words' }).click()
  await page.getByRole('button', { name: 'Back to my plan', exact: true }).click()
  await expect(page.getByLabel('A reminder for yourself')).toHaveValue('Fictional unfinished note: ąęł')
  await page.getByRole('button', { name: 'Back to introduction', exact: true }).first().click()
  await page.getByRole('button', { name: 'Continue my plan' }).click()
  await page.locator('.p-task-row').first().click()
  await page.getByRole('button', { name: /My update/ }).click()
  await expect(page.getByLabel('A reminder for yourself')).toHaveValue('Fictional unfinished note: ąęł')
  await expect(page.getByRole('button', { name: 'I’m not sure what I found' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Keep this update' }).click()
  await expect(page.locator('.p-task-row').first()).toContainText('Still a question')
  expect(await page.evaluate(() => JSON.stringify(history.state))).not.toMatch(/recovery|ąęł|unfinished/)
})

test('unsupported app and unknown starting point are useful paths, not blank plans', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start with my own situation' }).click()
  await page.getByRole('button', { name: 'Can someone see where I am?', exact: true }).click()
  await page.getByRole('button', { name: /^WhatsApp/ }).click()
  await page.getByRole('button', { name: 'Show my first step' }).click()
  await expect(page.getByRole('heading', { name: 'Choose someone to work through this with' })).toBeVisible()
  await expect(page.locator('.coverage-note')).toContainText('Location sharing')
  await nav(page, 'Find support').click()
  await page.getByLabel('Show support for').selectOption('poland')
  await expect(page.getByRole('link', { name: 'Visit Niebieska Linia' })).toHaveAttribute('href', 'https://www.niebieskalinia.pl/')
  await expect(page.getByRole('heading', { name: 'Support for young people' })).toBeVisible()
  await page.getByRole('button', { name: 'See private-image support' }).click()
  await expect(page.getByText(/If you were under 18 when an image was taken/)).toBeVisible()
  await page.getByRole('button', { name: 'Next instruction' }).click()
  await expect(page.getByText(/For adult images, visit StopNCII/)).toBeVisible()
})

test('removing and changing apps is explicit and undo survives an introduction visit', async ({ page }) => {
  await start(page)
  await nav(page, /^My plan/).click()
  await page.getByLabel('My note about the whole situation').fill('Fictional general note')
  await page.getByRole('button', { name: 'Remove this check: Keep a way back into your account', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Look at devices')
  await page.getByRole('button', { name: 'Keep this check', exact: true }).click()
  await expect(page.locator('.p-task-row')).toHaveCount(4)
  await page.getByRole('button', { name: 'Edit my apps and concerns' }).click()
  await page.getByRole('button', { name: /Google, Gmail or Google Photos/ }).click()
  await page.getByRole('button', { name: /^WhatsApp/ }).click()
  await page.getByRole('button', { name: 'Update my plan' }).click()
  await expect(page.getByRole('alert')).toContainText('These checks and their notes will be removed')
  await page.getByRole('button', { name: 'Use these choices' }).click()
  await page.getByRole('button', { name: 'Back to introduction', exact: true }).first().click()
  await page.getByRole('button', { name: 'Continue my plan' }).click()
  await page.getByRole('button', { name: 'Undo plan change' }).click()
  await expect(page.locator('.p-task-row')).toHaveCount(4)
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Fictional general note')
})

test('demo does not replace a personal plan; second companion draft adds checks', async ({ page }) => {
  await start(page)
  await nav(page, /^My plan/).click()
  await page.getByLabel('My note about the whole situation').fill('Only in my own plan')
  await page.getByRole('button', { name: 'Optional planning companion' }).click()
  await page.getByRole('button', { name: 'Google, Gmail or Google Photos', exact: true }).click()
  await page.getByRole('button', { name: 'Accounts & messages', exact: true }).click()
  await page.getByRole('button', { name: 'Photos & memories', exact: true }).click()
  await page.getByRole('button', { name: 'Build a draft on this device' }).click()
  await page.getByRole('button', { name: 'Keep these steps' }).click()
  await expect(page.locator('.u-kept')).toContainText('6 checks kept by you')
  await page.getByRole('button', { name: 'Untangle introduction' }).click()
  await page.getByRole('button', { name: 'Try Me', exact: true }).click()
  await page.locator('.u-working-panel').getByRole('button', { name: 'Connect the dots', exact: true }).click()
  await page.getByRole('button', { name: 'Keep these steps' }).click()
  await page.getByRole('button', { name: 'Open my full plan' }).click()
  await expect(page.locator('.p-example-banner')).toBeVisible()
  await expect(page.getByLabel('My note about the whole situation')).not.toHaveValue('Only in my own plan')
  await page.getByRole('button', { name: 'Optional planning companion' }).click()
  await expect(page.getByText('TRY ME · FICTIONAL EXAMPLE', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Open my full plan' }).click()
  await page.getByRole('button', { name: 'Return to my own plan' }).click()
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Only in my own plan')
  await expect(page.locator('.p-task-row')).toHaveCount(6)
})

test('save, check, return, edit and restore maintain honest file status', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: /My update/ }).click()
  await page.getByLabel('A reminder for yourself').fill('Fictional draft retained in file')
  await nav(page, 'Save & resume').click()
  await page.getByLabel('Create a file passphrase').fill('test phrase for an offline file')
  await page.getByLabel('Repeat the file passphrase').fill('test phrase for an offline file')
  await page.getByRole('button', { name: 'Show file passphrase', exact: true }).first().click()
  await expect(page.getByLabel('Create a file passphrase')).toHaveAttribute('type', 'text')
  const promise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download private plan' }).click()
  const download = await promise
  const file = fs.readFileSync((await download.path())!)
  await expect(page.locator('.session-status:visible')).toContainText('Download started')
  await page.getByLabel('Your .untangle file').setInputFiles({ name: 'my-plan.untangle', mimeType: 'application/json', buffer: file })
  await page.getByLabel('Its file passphrase').fill('test phrase for an offline file')
  await page.getByRole('button', { name: 'Open private plan' }).click()
  await expect(page.getByText('File opened successfully.', { exact: false })).toBeVisible()
  await expect(page.locator('.session-status:visible')).toContainText('Private copy checked')
  await page.getByRole('button', { name: 'Keep current plan' }).click()
  await nav(page, /^My plan/).click()
  await page.getByLabel('My note about the whole situation').fill('New unsaved work')
  await expect(page.locator('.session-status:visible')).toContainText('New changes')
  await page.reload()
  await expect(page.locator('.session-status:visible')).toContainText('Not saved to a file')
  await nav(page, 'Save & resume').click()
  await page.getByLabel('Your .untangle file').setInputFiles({ name: 'my-plan.untangle', mimeType: 'application/json', buffer: file })
  await page.getByLabel('Its file passphrase').fill('test phrase for an offline file')
  await page.getByRole('button', { name: 'Open private plan' }).click()
  await page.getByRole('button', { name: 'Use this saved plan' }).click()
  await page.locator('.p-task-row').first().click()
  await page.getByRole('button', { name: /My update/ }).click()
  await expect(page.getByLabel('A reminder for yourself')).toHaveValue('Fictional draft retained in file')
})

test('phone beginner controls, setup and contextual help work in English and Polish', async ({ page }) => {
  test.setTimeout(90000)
  for (const lang of ['en', 'pl']) {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto(`/?lang=${lang}`)
    const start = page.getByRole('button', { name: lang === 'en' ? 'Start with my own situation' : 'Zacznij od mojej sytuacji', exact: true })
    const bounds = await start.boundingBox()
    expect(bounds!.y + bounds!.height).toBeLessThan(844)
    await start.click()
    await page.getByRole('button', { name: lang === 'en' ? 'I’m not sure where to start' : 'Nie wiem, od czego zacząć', exact: true }).click()
    const disclosure = page.locator('.guided-steps summary')
    await disclosure.click()
    await page.locator('.guide-help-options button').nth(1).click()
    await expect(page.locator('.guided-steps')).toContainText(lang === 'en' ? 'Untangle has no login' : 'Untangle nie wymaga logowania')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([])
  }
})

test('explicitly clearing the plan also removes an unaccepted companion wording draft', async ({ page }) => {
  await page.route('**/api/agent/status', route => route.fulfill({ json: { available: true, model: 'test' } }))
  await page.route('**/api/agent', route => route.fulfill({ contentType: 'application/x-ndjson', body: JSON.stringify({ stage: 'ready', message: 'Draft ready.', draft: { taskIds: [], editedText: 'A fictional pending wording draft.' } }) + '\n' }))
  await start(page)
  await nav(page, /^My plan/).click()
  await page.getByRole('button', { name: 'Optional planning companion' }).click()
  await page.getByRole('button', { name: 'Google, Gmail or Google Photos', exact: true }).click()
  await page.getByRole('button', { name: 'Help me put it into words' }).click()
  await page.getByLabel('A note for yourself').fill('A fictional sensitive test note.')
  await page.getByRole('button', { name: 'Ask AI to simplify this note' }).click()
  await page.getByRole('dialog').getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Send these fields' }).click()
  await expect(page.getByLabel('You can edit this draft too')).toHaveValue('A fictional pending wording draft.')
  await page.getByRole('button', { name: 'Untangle introduction' }).click()
  await page.getByRole('button', { name: 'Continue my plan' }).click()
  await page.getByRole('button', { name: 'Clear plan', exact: true }).click()
  await page.getByRole('button', { name: 'Clear and start fresh' }).click()
  await expect(page.getByRole('button', { name: 'Make my own plan', exact: true })).toBeVisible()
  await expect(page.locator('#edit-draft')).toHaveCount(0)
  await expect(page.locator('#companion-note')).toHaveCount(0)
  await expect(page.locator('.session-status:visible')).toContainText('Not saved to a file')
})

test('undoing an imported fictional file returns to the exact personal plan and mode', async ({ page }) => {
  const { encryptPlan } = await import('../../src/features/plan/crypto')
  const { examplePlan } = await import('../../src/features/plan/model')
  await start(page)
  await nav(page, /^My plan/).click()
  await page.getByLabel('My note about the whole situation').fill('My fictional original note')
  await nav(page, 'Save & resume').click()
  const fixture = await encryptPlan(examplePlan(), 'a phrase only for testing')
  await page.getByLabel('Your .untangle file').setInputFiles({ name: 'example.untangle', mimeType: 'application/json', buffer: Buffer.from(fixture) })
  await page.getByLabel('Its file passphrase').fill('a phrase only for testing')
  await page.getByRole('button', { name: 'Open private plan' }).click()
  await page.getByRole('button', { name: 'Use this saved plan' }).click()
  await expect(page.locator('.p-example-banner')).toBeVisible()
  await page.getByRole('button', { name: 'Undo plan change' }).click()
  await expect(page.locator('.p-example-banner')).toHaveCount(0)
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('My fictional original note')
  await expect(page.locator('.p-task-row')).toHaveCount(4)
})
