import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { encryptPlan } from '../../src/features/plan/crypto'
import { buildPlan } from '../../src/features/plan/model'

const button = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
const planNav = (page: Page, name: string | RegExp) => page.getByRole('navigation', { name: 'Plan navigation' }).getByRole('button', { name })
async function personal(page: Page) {
  await page.goto('/')
  await button(page, 'Start with my own situation').click()
  await button(page, 'Who can get into my accounts?').click()
  await page.getByRole('button', { name: /Google, Gmail or Google Photos/ }).click()
  await button(page, 'Show my first step').click()
  await expect(page.getByRole('heading', { name: 'Keep a way back into your account', exact: true })).toBeFocused()
  await planNav(page, /^My plan/).click()
  await expect(page.getByLabel('My note about the whole situation')).toBeVisible()
}

test('unfinished setup survives the introduction and stays separate from example setup', async ({ page }) => {
  await page.goto('/')
  await button(page, 'Start with my own situation').click()
  await button(page, 'What happens to our photos?').click()
  await page.getByRole('button', { name: /Google, Gmail or Google Photos/ }).click()
  await page.getByRole('banner').getByRole('button', { name: 'Back to introduction' }).click()
  await button(page, 'Start with my own situation').click()
  await expect(button(page, 'What happens to our photos?')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /Google, Gmail or Google Photos/ })).toHaveAttribute('aria-pressed', 'true')
  await button(page, 'Demo walkthrough').click()
  for (const name of ['Build Maya’s draft', 'Preview a change', 'Try wording help', 'Keep original', 'Keep this demo plan', 'Open example plan']) await button(page, name).click()
  await button(page, 'Edit my apps and concerns').click()
  await page.getByRole('button', { name: /^An iPhone/ }).click()
  await button(page, 'Return to my own plan').click()
  await button(page, 'Make my own plan').click()
  await expect(button(page, 'What happens to our photos?')).toHaveAttribute('aria-pressed', 'true')
  await expect(button(page, 'Who can get into my accounts?')).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: /^An iPhone/ })).toHaveAttribute('aria-pressed', 'false')
})

test('practice wording undo cannot alter a personal note', async ({ page }) => {
  await personal(page)
  await page.getByLabel('My note about the whole situation').fill('My own fictional note must stay here')
  await page.getByRole('banner').getByRole('button', { name: 'Back to introduction' }).click()
  await button(page, 'Try Me').click()
  await page.locator('.u-working-panel').getByRole('button', { name: 'Connect the dots', exact: true }).click()
  await button(page, 'Keep these steps').click()
  await button(page, 'Help me put it into words').click()
  await button(page, 'Preview the example edit').click()
  await button(page, 'Use this wording').click()
  await expect(button(page, 'Undo wording change')).toBeVisible()
  await page.getByRole('navigation', { name: 'Assistant tools' }).getByRole('button', { name: 'Connect the dots', exact: true }).click()
  await button(page, 'Open my full plan').click()
  await button(page, 'Return to my own plan').click()
  await button(page, 'Optional planning companion').click()
  await button(page, 'Help me put it into words').click()
  await expect(page.getByLabel('A note for yourself')).toHaveValue('My own fictional note must stay here')
  await expect(button(page, 'Undo wording change')).toHaveCount(0)
})

test('the unsure setup path confirms removal of existing checks and notes', async ({ page }) => {
  await personal(page)
  await button(page, 'Edit my apps and concerns').click()
  await button(page, 'I’m not sure where to start').click()
  await expect(page.getByRole('alert')).toContainText('These checks and their notes will be removed')
  await button(page, 'Keep editing').click()
  await expect(page.locator('.plan-setup')).toBeVisible()
  await button(page, 'I’m not sure where to start').click()
  await button(page, 'Use these choices').click()
  await expect(page.getByRole('heading', { name: 'Choose someone to work through this with', exact: true })).toBeVisible()
  await planNav(page, /^My plan/).click()
  await button(page, 'Undo plan change').click()
  await expect(page.locator('.p-task-row')).toHaveCount(4)
})

test('navigation targets remain below the sticky header after scrolling', async ({ page }) => {
  for (const width of [390, 768, 1280]) {
    await page.setViewportSize({ width, height: 720 })
    await personal(page)
    await page.locator('.p-task-row').first().click()
    const nav = planNav(page, /^My plan/)
    await nav.scrollIntoViewIfNeeded()
    const bounds = await nav.boundingBox(), header = await page.locator('.header-wrap').boundingBox()
    expect(bounds!.y, `navigation below header at ${width}`).toBeGreaterThanOrEqual(header!.y + header!.height)
    await nav.click()
    await expect(page.getByLabel('My note about the whole situation')).toBeVisible()
  }
})

test('file selection and passphrase cannot change while a private file is opening', async ({ page }) => {
  await page.addInitScript(() => {
    const decrypt = SubtleCrypto.prototype.decrypt
    SubtleCrypto.prototype.decrypt = async function (...args) {
      await new Promise<void>(resolve => { (window as unknown as { finishDecrypt: () => void }).finishDecrypt = resolve })
      return decrypt.apply(this, args)
    }
  })
  const file = await encryptPlan({ ...buildPlan(['photos'], ['google']), note: 'A fictional imported note' }, 'A phrase for audit testing')
  await page.goto('/?view=plan')
  await planNav(page, 'Save & resume').click()
  await page.getByLabel('Your .untangle file').setInputFiles({ name: 'audit.untangle', mimeType: 'application/json', buffer: Buffer.from(file) })
  await page.getByLabel('Its file passphrase').fill('A phrase for audit testing')
  await button(page, 'Open private plan').click()
  await expect(page.getByLabel('Your .untangle file')).toBeDisabled()
  await expect(page.getByLabel('Its file passphrase')).toBeDisabled()
  await expect.poll(() => page.evaluate(() => typeof (window as unknown as { finishDecrypt?: () => void }).finishDecrypt)).toBe('function')
  await page.evaluate(() => (window as unknown as { finishDecrypt: () => void }).finishDecrypt())
  await expect(button(page, 'Use this saved plan')).toBeVisible()
  await expect(page.getByLabel('Your .untangle file')).toBeEnabled()
})

async function prepareEditor(page: Page) {
  await page.route('**/api/agent/status', route => route.fulfill({ json: { available: true, model: 'audit-fixture' } }))
  await personal(page)
  await button(page, 'Optional planning companion').click()
  await button(page, 'Google, Gmail or Google Photos').click()
  await button(page, 'Help me put it into words').click()
  await page.getByLabel('A note for yourself').fill('A fictional question about a shared laptop.')
  await button(page, 'Ask AI to simplify this note').click()
  await page.getByRole('dialog').getByRole('checkbox').check()
  await button(page, 'Send these fields').click()
}
const editedStream = JSON.stringify({ stage: 'ready', message: 'Draft ready.', draft: { taskIds: [], editedText: 'A clearer fictional question about the laptop.' } }) + '\n'

test('a later manual note change invalidates earlier wording undo', async ({ page }) => {
  await page.route('**/api/agent', route => route.fulfill({ contentType: 'application/x-ndjson', body: editedStream }))
  await prepareEditor(page)
  await button(page, 'Use this wording').click()
  await expect(button(page, 'Undo wording change')).toBeVisible()
  await button(page, 'Untangle introduction').click()
  await button(page, 'Continue my plan').click()
  await page.getByLabel('My note about the whole situation').fill('A newer fictional note written in my plan.')
  await button(page, 'Optional planning companion').click()
  await button(page, 'Help me put it into words').click()
  await expect(page.getByLabel('A note for yourself')).toHaveValue('A newer fictional note written in my plan.')
  await expect(button(page, 'Undo wording change')).toHaveCount(0)
})

test('leaving the companion cancels a pending response instead of reviving an old edit', async ({ page }) => {
  let release: () => void = () => {}, sent = false
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/agent', async route => { sent = true; await gate; await route.fulfill({ contentType: 'application/x-ndjson', body: editedStream }).catch(() => {}) })
  await prepareEditor(page)
  await expect.poll(() => sent).toBe(true)
  await button(page, 'Demo walkthrough').click()
  release()
  await button(page, 'Exit demo').click()
  await expect(button(page, 'Ask AI to simplify this note')).toBeEnabled()
  await expect(page.getByLabel('You can edit this draft too')).toHaveCount(0)
  await expect(page.getByLabel('A note for yourself')).toHaveValue('A fictional question about a shared laptop.')
})

test('undoing an imported example restores the displaced example and keeps the current personal plan', async ({ page }) => {
  await personal(page)
  await page.getByLabel('My note about the whole situation').fill('Personal note before import')
  await button(page, 'Demo walkthrough').click()
  for (const name of ['Build Maya’s draft', 'Preview a change', 'Try wording help', 'Keep original', 'Keep this demo plan', 'Open example plan']) await button(page, name).click()
  await page.getByLabel('My note about the whole situation').fill('The previous example must survive undo')
  await button(page, 'Return to my own plan').click()
  await planNav(page, 'Save & resume').click()
  const file = await encryptPlan({ ...buildPlan(['photos'], ['google']), example: true, note: 'Replacement example' }, 'A phrase for audit testing')
  await page.getByLabel('Your .untangle file').setInputFiles({ name: 'example.untangle', mimeType: 'application/json', buffer: Buffer.from(file) })
  await page.getByLabel('Its file passphrase').fill('A phrase for audit testing')
  await button(page, 'Open private plan').click()
  await button(page, 'Use this saved plan').click()
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Replacement example')
  await button(page, 'Return to my own plan').click()
  await page.getByLabel('My note about the whole situation').fill('Personal note after import')
  await page.goBack()
  await button(page, 'Undo plan change').click()
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Personal note after import')
  await page.getByRole('banner').getByRole('button', { name: 'Back to introduction' }).click()
  await button(page, 'Try Me').click()
  await expect(page.locator('.u-kept')).toContainText('6 checks kept by you')
  await button(page, 'Help me put it into words').click()
  await expect(page.getByLabel('Maya’s example note')).toHaveValue('The previous example must survive undo')
})

test('quick exit remains available when the walkthrough is scrolled on a short phone screen', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 568 })
  await page.goto('/?lang=pl&view=demo')
  await page.locator('.jt-footer').scrollIntoViewIfNeeded()
  await expect(page.locator('.jt-quick-exit')).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('a failed plan download shows recovery and still lets the user save their session', async ({ page }) => {
  await page.route('**/assets/LegacyApp-*.js', route => route.abort('failed'))
  await page.goto('/?view=assistant')
  await button(page, 'Google, Gmail or Google Photos').click()
  await button(page, 'Build a draft on this device').click()
  await button(page, 'Keep these steps').click()
  await button(page, 'Help me put it into words').click()
  await page.getByLabel('A note for yourself').fill('My fictional work survives a loading error')
  await page.getByRole('navigation', { name: 'Assistant tools' }).getByRole('button', { name: 'Connect the dots', exact: true }).click()
  await button(page, 'Open my full plan').click()
  await expect(page.getByRole('alert')).toContainText('This page couldn’t open')
  await expect(page.getByRole('alert')).toBeFocused()
  for (const width of [320, 1280]) {
    await page.setViewportSize({ width, height: 800 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  }
  await page.getByLabel('Create a file passphrase').fill('A phrase for audit testing')
  await page.getByLabel('Repeat the file passphrase').fill('A phrase for audit testing')
  const download = page.waitForEvent('download')
  await button(page, 'Download private plan').click()
  const path = await (await download).path()
  const { readFile } = await import('node:fs/promises')
  const { decryptPlan } = await import('../../src/features/plan/crypto')
  expect((await decryptPlan(await readFile(path!, 'utf8'), 'A phrase for audit testing')).note).toBe('My fictional work survives a loading error')
  await button(page, 'Back to introduction').click()
  await expect(button(page, 'Continue my plan')).toBeVisible()
})

test('example sharing and removal choices do not carry into the personal workspace', async ({ page }) => {
  await personal(page)
  await page.getByLabel('My note about the whole situation').fill('A private fictional personal reminder')
  await button(page, 'Demo walkthrough').click()
  for (const name of ['Build Maya’s draft', 'Preview a change', 'Try wording help', 'Keep original', 'Keep this demo plan', 'Open example plan']) await button(page, name).click()
  await planNav(page, 'Review together').click()
  await page.getByLabel('Show my notes here').check()
  await button(page, 'Return to my own plan').click()
  await planNav(page, 'Review together').click()
  await expect(page.getByLabel('Show my notes here')).not.toBeChecked()
  await expect(page.getByText('A private fictional personal reminder', { exact: true })).toHaveCount(0)
  await planNav(page, /^My plan/).click()
  await button(page, 'Clear plan').click()
  await button(page, 'Demo walkthrough').click()
  for (const name of ['Build Maya’s draft', 'Preview a change', 'Try wording help', 'Keep original', 'Keep this demo plan', 'Open example plan']) await button(page, name).click()
  await expect(button(page, 'Clear and start fresh')).toHaveCount(0)
})
