import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

const launch = (page: Page) => page.getByRole('button', { name: 'Demo walkthrough', exact: true })
const button = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
async function toWording(page: Page) {
  await button(page, 'Build Maya’s draft').click()
  await button(page, 'Preview a change').click()
  await button(page, 'Try wording help').click()
}

test('judge tour uses the selected checks and edited wording, and only keeps a plan after approval', async ({ page, baseURL }) => {
  const calls: string[] = []
  page.on('request', request => { if (request.url().includes('/api/') || new URL(request.url()).origin !== new URL(baseURL!).origin) calls.push(request.url()) })
  await page.goto('/')
  await expect(launch(page)).toBeInViewport()
  await launch(page).click()
  await expect(page).toHaveURL(/view=demo/)
  await expect(page.locator('#demo-heading')).toBeFocused()
  await button(page, 'Build Maya’s draft').click()
  await expect(page.getByRole('checkbox')).toHaveCount(6)
  await expect(page.getByRole('checkbox', { name: /Keep a way back/ })).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Check whether your emails go somewhere else', exact: true }).uncheck()
  await expect(page.getByRole('status')).toHaveText('Selected checks: 5')
  await button(page, 'Preview a change').click()
  await expect(page.locator('.jt-effect-limit')).toContainText('saved photo copies')
  await expect(page.getByRole('link', { name: /Google: change or reset a password/ })).toHaveAttribute('href', 'https://support.google.com/accounts/answer/41078?hl=en')
  await button(page, 'Try wording help').click()
  await page.getByLabel('Suggested wording · Edit if you like').fill('Fictional judge note: check the laptop first.')
  await button(page, 'Use this wording').click()
  await expect(page.locator('.jt-summary-list li')).toHaveCount(5)
  await expect(page.locator('.jt-work .jt-note')).toContainText('Fictional judge note: check the laptop first.')
  await button(page, 'Keep this demo plan').click()
  await expect(page.locator('.jt-success')).toContainText('Checks in the plan: 5 · Account changes: 0')
  await expect(page.locator('.jt-pending')).toHaveText('Not checked yet')
  await button(page, 'Open example plan').click()
  await expect(page.locator('.p-example-banner')).toBeVisible()
  await expect(page.locator('.p-task-row')).toHaveCount(5)
  await expect(page.locator('.p-progress-count')).toHaveText('0 / 5')
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Fictional judge note: check the laptop first.')
  expect(calls).toEqual([])
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
  expect(await page.evaluate(() => JSON.stringify(history.state) + location.href)).not.toMatch(/Fictional judge|laptop|recovery/)
})

test('exit, restart, finish and opening a result preserve personal notes and unfinished updates', async ({ page }) => {
  await page.goto('/')
  await button(page, 'Start with my own situation').click()
  await button(page, 'Who can get into my accounts?').click()
  await page.getByRole('button', { name: /Google, Gmail or Google Photos/ }).click()
  await button(page, 'Show my first step').click()
  await page.getByRole('button', { name: /My update/ }).click()
  await button(page, 'I’m not sure what I found').click()
  await page.getByLabel('A reminder for yourself').fill('Personal unfinished reminder')
  await launch(page).click()
  await toWording(page)
  await button(page, 'Exit demo').click()
  await expect(page.getByLabel('A reminder for yourself')).toHaveValue('Personal unfinished reminder')
  await page.getByRole('navigation', { name: 'Plan navigation' }).getByRole('button', { name: /^My plan/ }).click()
  await page.getByLabel('My note about the whole situation').fill('Keep my personal plan intact')
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Keep my personal plan intact')
  await launch(page).click()
  await toWording(page)
  await page.getByLabel('Suggested wording · Edit if you like').fill('Discard this fictional draft on restart')
  await button(page, 'Restart tour').click()
  await toWording(page)
  await expect(page.getByLabel('Suggested wording · Edit if you like')).not.toHaveValue('Discard this fictional draft on restart')
  await button(page, 'Keep original').click()
  await expect(page.locator('.jt-work .jt-note')).toContainText('Original wording kept')
  await button(page, 'Keep this demo plan').click()
  await button(page, 'Finish tour').click()
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Keep my personal plan intact')
  await launch(page).click()
  await toWording(page)
  await button(page, 'Keep original').click()
  await button(page, 'Keep this demo plan').click()
  await button(page, 'Open example plan').click()
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('I changed my password but I don’t know about that laptop or our photos.')
  await button(page, 'Return to my own plan').click()
  await expect(page.getByLabel('My note about the whole situation')).toHaveValue('Keep my personal plan intact')
  await expect(page.locator('.p-task-row')).toHaveCount(4)
  await page.locator('.p-task-row').first().click()
  await page.getByRole('button', { name: /My update/ }).click()
  await expect(page.getByLabel('A reminder for yourself')).toHaveValue('Personal unfinished reminder')
})

test('tour handles empty choices, preparation dependencies, back, and browser history', async ({ page }) => {
  await page.goto('/')
  await launch(page).click()
  await button(page, 'Build Maya’s draft').click()
  // Remove dependents first, then their now-optional preparation checks.
  for (const name of ['Look at devices using your Google account', 'Understand what changing a password does', 'Check whether your emails go somewhere else', 'Review Google Photos partner sharing', 'Keep a way back into your account', 'Decide what you want to keep']) {
    await page.getByRole('checkbox', { name, exact: true }).uncheck()
  }
  await expect(button(page, 'Preview a change')).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Understand what changing a password does', exact: true }).check()
  await expect(page.getByRole('status')).toHaveText('Selected checks: 2')
  await expect(page.getByRole('checkbox', { name: /Keep a way back/ })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: /Keep a way back/ })).toBeDisabled()
  await button(page, 'Preview a change').click()
  await button(page, 'Previous step').click()
  await expect(page.getByRole('status')).toHaveText('Selected checks: 2')
  await page.goBack()
  await expect(launch(page)).toBeVisible()
  await page.goForward()
  await expect(page.locator('#demo-heading')).toHaveText('One story. One clear route.')
})

test('visible launch fits all headers and phone widths in both languages', async ({ page }) => {
  test.setTimeout(90000)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const locale of ['en', 'pl']) for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto(`/?lang=${locale}`)
    const name = locale === 'en' ? 'Demo walkthrough' : 'Demo krok po kroku'
    await expect(button(page, name)).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.locator('.u-intro-actions .u-primary').click()
    await expect(button(page, name)).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await button(page, name).click()
    await expect(page.locator('#demo-heading')).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
})

test('all stages are accessible in English and Polish, and language switching preserves editing', async ({ page }) => {
  test.setTimeout(120000)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const locale of ['en', 'pl']) {
    await page.setViewportSize({ width: locale === 'en' ? 1280 : 390, height: 900 })
    await page.goto(`/?view=demo&lang=${locale}`)
    const actions = locale === 'en' ? ['Build Maya’s draft', 'Preview a change', 'Try wording help', 'Use this wording', 'Keep this demo plan'] : ['Przygotuj propozycję dla Mai', 'Zobacz skutki zmiany', 'Wypróbuj pomoc w pisaniu', 'Użyj tej treści', 'Zachowaj ten plan demo']
    for (let step = 0; step < 6; step++) {
      await expect(page.locator('#demo-heading')).toBeFocused()
      await expect(page.locator('.jt-progress [aria-current="step"]')).toHaveCount(1)
      expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(locale === 'en' ? 1280 : 390)
      expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
      if (step < 5) await button(page, actions[step]).click()
    }
    await expect(page.locator('.jt-success')).toContainText(locale === 'en' ? 'Walkthrough complete' : 'Prezentacja zakończona')
  }
  await page.goto('/?view=demo&lang=en')
  await toWording(page)
  await button(page, 'Polski').click()
  await expect(page.locator('#demo-wording')).not.toHaveValue(/I changed my password/)
  await page.locator('#demo-wording').fill('Moja próbna notatka — ąęł')
  await button(page, 'English').click()
  await expect(page.locator('#demo-wording')).toHaveValue('Moja próbna notatka — ąęł')
  await page.locator('#demo-wording').fill('   ')
  await expect(button(page, 'Use this wording')).toBeDisabled()
  await button(page, 'Keep original').click()
  await expect(page.locator('.jt-work .jt-note')).toContainText('I changed my password but I don’t know')
})
