import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('language switch keeps the draft, topics and exact personal notes, without browser storage', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start with my own situation' }).click()
  await page.getByRole('button', { name: 'Build a draft on this device' }).click()
  await page.getByRole('button', { name: 'Polski', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'pl')
  await expect(page).toHaveURL(/lang=pl/)
  await expect(page.getByRole('heading', { name: 'Propozycja czeka na Twoją decyzję.' })).toBeVisible()
  await expect(page.locator('.u-draft-list input')).toHaveCount(6)
  await page.getByRole('button', { name: 'Zachowaj te kroki' }).click()
  await expect(page.locator('.u-kept')).toContainText('Zachowane kroki: 6')
  await page.getByRole('button', { name: 'Pomóż mi ubrać to w słowa' }).click()
  const note = 'Back — zachowaj mój dokładny tekst: ąęłóśćźż.'
  await page.getByLabel('Notatka dla siebie').fill(note)
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page.getByLabel('A note for yourself')).toHaveValue(note)
  await page.getByRole('navigation', { name: 'Assistant tools' }).getByRole('button', { name: 'Connect the dots', exact: true }).click()
  await page.getByRole('button', { name: 'Polski', exact: true }).click()
  await page.getByRole('button', { name: 'Otwórz mój pełny plan' }).click()
  await expect(page.getByRole('heading', { name: 'Wystarczy po trochu.' })).toBeVisible()
  await page.locator('.p-task-row').first().click()
  await page.getByRole('button', { name: '3 Mój wpis' }).click()
  await expect(page.getByLabel('Przypomnienie dla siebie')).toHaveValue(note)
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page.getByLabel('A reminder for yourself')).toHaveValue(note)
  expect(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }))).toEqual({ local: 0, session: 0 })
})

test('Polish guide search, examples, help and save errors; URL retains view on refresh', async ({ page }) => {
  await page.goto('/?view=plan&lang=pl')
  await page.getByRole('button', { name: 'Przeglądaj poradniki', exact: true }).click()
  await page.getByRole('searchbox').fill('zdjęć')
  await expect(page.locator('.p-guide-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page).toHaveURL(/view=plan&lang=en/)
  await page.getByRole('button', { name: 'Polski', exact: true }).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang', 'pl')
  await page.getByRole('button', { name: 'Zobacz przykładowy plan Mai' }).click()
  await page.getByRole('button', { name: 'Zapisz i wróć później', exact: true }).click()
  await page.getByLabel('Utwórz hasło do pliku').fill('fictional test password')
  await page.getByLabel('Powtórz hasło do pliku').fill('different test password')
  await page.getByRole('button', { name: 'Pobierz prywatny plan' }).click()
  await expect(page.getByRole('alert')).toHaveText('Podane hasła nie są takie same.')
  await page.getByRole('button', { name: 'Pomoc i pojęcia' }).click()
  await expect(page.getByRole('heading', { name: 'Możesz dopiero to poznawać.' })).toBeVisible()
})

test('Polish walkthrough and fictional editor have translated content', async ({ page }) => {
  await page.goto('/?view=walkthrough&lang=pl')
  await page.getByRole('button', { name: 'Wypróbuj bez używania mojego konta' }).click()
  await page.getByRole('button', { name: 'Pokaż mi przykład' }).click()
  await expect(page.getByRole('heading', { name: 'Oto fikcyjna lista urządzeń.' })).toBeVisible()
  await page.getByRole('button', { name: 'Widzę przykładową listę' }).click()
  await page.getByRole('button', { name: 'Przyjrzyj się wspólnemu laptopowi' }).click()
  await page.getByRole('button', { name: 'Wyjaśnij ten przykład' }).click()
  await expect(page.getByRole('heading', { name: 'Ta sesja może być nadal aktywna.' })).toBeVisible()
  await page.goto('/?lang=pl')
  await page.getByRole('button', { name: 'Wypróbuj', exact: true }).click()
  await page.getByRole('button', { name: 'Pomóż mi ubrać to w słowa' }).click()
  await expect(page.getByLabel('Przykładowa notatka Mai')).toHaveValue(/Zmieniłam hasło/)
  await page.getByRole('button', { name: 'Zobacz przykładową poprawkę' }).click()
  await expect(page.getByLabel('Tę propozycję też możesz poprawić')).toHaveValue(/Muszę jeszcze sprawdzić/)
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByLabel('You can edit this draft too').fill('Back')
  await page.getByRole('button', { name: 'Use this wording' }).click()
  await page.getByRole('button', { name: 'Polski', exact: true }).click()
  await expect(page.getByLabel('Przykładowa notatka Mai')).toHaveValue('Back')
})

test('Polish AI request shows and sends the chosen response language only after consent', async ({ page }) => {
  let sent: Record<string, unknown> | undefined
  await page.route('**/api/agent/status', route => route.fulfill({ json: { available: true, model: 'test' } }))
  await page.route('**/api/agent', route => {
    sent = route.request().postDataJSON()
    return route.fulfill({ contentType: 'application/x-ndjson', body: JSON.stringify({ stage: 'ready', message: 'Draft ready for your review. Accept, edit or discard it.', draft: { taskIds: ['devices'], editedText: 'Nie wiem, który laptop jest mój.' } }) + '\n' })
  })
  await page.goto('/?lang=pl')
  await page.getByRole('button', { name: 'Zacznij od mojej sytuacji' }).click()
  await page.getByRole('button', { name: 'Pomóż mi ubrać to w słowa' }).click()
  await page.getByLabel('Notatka dla siebie').fill('Nie wiem co z tym laptopem.')
  await page.getByRole('button', { name: 'Poproś AI o uproszczenie notatki' }).click()
  await expect(page.getByRole('dialog')).toContainText('Język odpowiedzi')
  await expect(page.getByRole('dialog')).toContainText('Polski')
  expect(sent).toBeUndefined()
  await page.getByRole('dialog').getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Wyślij te pola' }).click()
  await expect(page.getByLabel('Tę propozycję też możesz poprawić')).toHaveValue('Nie wiem, który laptop jest mój.')
  expect(sent).toMatchObject({ locale: 'pl', consent: true, text: 'Nie wiem co z tym laptopem.' })
  await expect(page.getByLabel('Notatka dla siebie')).toHaveValue('Nie wiem co z tym laptopem.')
})

test('Polish switch stays visible and accessible on phone and desktop', async ({ page }) => {
  test.setTimeout(120000)
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/?lang=pl')
    const control = page.getByRole('button', { name: 'Polski', exact: true })
    await expect(control).toBeVisible()
    expect((await control.boundingBox())!.y).toBeLessThan(200)
    for (const state of ['intro', 'draft', 'plan']) {
      if (state === 'draft') {
        await page.getByRole('button', { name: 'Wypróbuj', exact: true }).click()
        await page.locator('.u-working-panel').getByRole('button', { name: 'Połącz fakty', exact: true }).click()
      }
      if (state === 'plan') {
        await page.getByRole('button', { name: 'Zachowaj te kroki' }).click()
        await page.getByRole('button', { name: 'Otwórz mój pełny plan' }).click()
      }
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${width} ${state}`).toBe(true)
      expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
      if (width === 390 || width === 1440) await page.screenshot({ path: `docs/screenshots/polish-${state}-${width}.png`, fullPage: true, animations: 'disabled' })
    }
  }
})

test('research switches languages and returns to the app in Polish', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/research.html')
  await page.getByRole('link', { name: 'Polski', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'pl')
  await expect(page.locator('h2')).toHaveCount(10)
  await expect(page.getByRole('heading', { name: '3. Korzystanie z produktów: co naprawdę mierzą liczby' })).toBeVisible()
  await expect(page.locator('body')).toContainText('332 527')
  await expect(page.locator('body')).toContainText('17 653')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.getByRole('link', { name: '← Otwórz Untangle' }).click()
  await expect(page.getByRole('button', { name: 'Wypróbuj', exact: true })).toBeVisible()
  await expect(page).toHaveURL(/lang=pl/)
})
