import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import fs from 'node:fs'
import { encryptPlan } from '../../src/features/plan/crypto'
import { examplePlan } from '../../src/features/plan/model'

async function personal(page: Page) {
  await page.goto('/?view=plan')
  await page.getByRole('button', { name: 'Make my own plan', exact: true }).click()
  await page.getByRole('button', { name: /Who can get into my accounts/ }).click()
  await page.getByRole('button', { name: /Can someone see where I am/ }).click()
  await page.getByRole('button', { name: /Google, Gmail or Google Photos/ }).click()
  await page.getByRole('button', { name: 'Show my first step', exact: true }).click()
  await page.getByRole('navigation', { name: 'Plan navigation' }).getByRole('button', { name: 'My plan 5', exact: true }).click()
}
const nav = (page: Page, name: string) => page.getByRole('navigation', { name: 'Plan navigation' }).getByRole('button', { name, exact: true })
async function capture(page: Page, name: string) { await page.locator('.loading-page').waitFor({ state: 'detached' }); await page.evaluate(() => document.fonts.ready); await page.screenshot({ path: `docs/screenshots/platform-${name}.png`, fullPage: true, animations: 'disabled' }) }

test('personal concerns and apps build a relevant plan; preview does not mark checks reviewed', async ({ page }) => {
  await personal(page)
  await expect(page.locator('.p-task-list')).toContainText('Google Maps')
  await expect(page.locator('.p-task-list')).not.toContainText('iPhone')
  await expect(page.locator('.p-task-list')).not.toContainText('WhatsApp')
  await expect(page.locator('.p-next')).toContainText('Keep a way back')
  await page.getByRole('button', { name: /Understand what changing a password does Google/ }).click()
  await page.getByRole('button', { name: /Before a change/ }).click()
  await expect(page.locator('.p-dependency')).toContainText('Keep a way back')
  await expect(page.locator('.p-task-heading .p-badge')).toHaveText('Not checked yet')
  await page.getByRole('button', { name: 'Keep a way back into your account', exact: true }).click()
  await expect(page.locator('#platform-heading')).toBeFocused()
  await expect(page.locator('#platform-heading')).toHaveText('Keep a way back into your account')
  await nav(page, 'My plan 5').click()
  await expect(page.locator('.p-progress-count')).toContainText('0 / 5')
})

test('uncertainty survives navigation and handoff hides notes until requested; history supports rechecks', async ({ page }) => {
  await personal(page)
  await page.getByRole('button', { name: 'Take this step', exact: true }).click()
  await page.getByRole('button', { name: /My update/ }).click()
  await page.getByRole('button', { name: 'I’m not sure what I found' }).click()
  await page.getByLabel('A reminder for yourself').fill('Fictional test: ask about the old phone')
  await page.getByRole('button', { name: 'Keep this update', exact: true }).click()
  await expect(page.locator('.p-task-list')).toContainText('Still a question')
  await nav(page, 'Review together').click()
  await expect(page.getByText('Fictional test: ask about the old phone', { exact: true })).toHaveCount(0)
  await page.getByLabel('Show my notes here').check()
  await expect(page.getByText('Fictional test: ask about the old phone', { exact: true })).toBeVisible()
  await page.locator('.p-handoff-list section').filter({ hasText: 'Keep a way back into your account' }).getByRole('button').click()
  await page.getByRole('button', { name: /My update/ }).click()
  await page.getByRole('button', { name: 'I checked how I would get back in' }).click()
  await page.getByRole('button', { name: 'Keep this update' }).click()
  await page.getByRole('button', { name: /Keep a way back into your account Google/ }).click()
  await page.getByText('Previous updates (2)', { exact: true }).click()
  await expect(page.locator('.p-history')).toHaveCount(2)
  await expect(page.locator('.p-history').last()).toContainText('Still a question')
})

test('save downloads encrypted content; incorrect import never replaces the active plan', async ({ page }) => {
  await personal(page)
  await nav(page, 'Save & resume').click()
  await page.getByLabel('Create a file passphrase').fill('made up test phrase only')
  await page.getByLabel('Repeat the file passphrase').fill('made up test phrase only')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download private plan' }).click()
  const download = await downloadPromise
  const encrypted = fs.readFileSync((await download.path())!, 'utf8')
  expect(encrypted).not.toContain('recovery')
  expect(encrypted).not.toContain('made up test phrase only')
  expect(JSON.parse(encrypted).cipher).toBe('AES-GCM')
  await expect(page.getByLabel('Create a file passphrase')).toHaveValue('')
  const fixture = await encryptPlan(examplePlan(), 'example import passphrase')
  await page.getByLabel('Your .untangle file').setInputFiles({ name: 'example.untangle', mimeType: 'application/json', buffer: Buffer.from(fixture) })
  await page.getByLabel('Its file passphrase').fill('incorrect')
  await page.getByRole('button', { name: 'Open private plan' }).click()
  await expect(page.getByRole('alert')).toContainText('Could not open')
  await expect(nav(page, 'My plan 5')).toBeVisible()
  await page.getByLabel('Its file passphrase').fill('example import passphrase')
  await page.getByRole('button', { name: 'Open private plan' }).click()
  await expect(page.getByRole('heading', { name: 'Ready to open a fictional example' })).toBeVisible()
  await page.getByRole('button', { name: 'Use this saved plan' }).click()
  await expect(page.locator('.p-example-banner')).toBeVisible()
  await expect(page.locator('.p-task-list')).toContainText('Still a question')
  await expect(page.locator('.p-progress-count')).toContainText('1 / 9')
})

test('no silent persistence or third-party calls; pagehide and exit clear the workspace', async ({ page }) => {
  const externalRequests: string[] = []
  page.on('request', request => { if (!new URL(request.url()).hostname.match(/^(127\.0\.0\.1|localhost)$/)) externalRequests.push(request.url()) })
  await personal(page)
  expect(await page.evaluate(async () => ({ local: localStorage.length, session: sessionStorage.length, db: (await indexedDB.databases()).length, sw: (await navigator.serviceWorker.getRegistrations()).length }))).toEqual({ local: 0, session: 0, db: 0, sw: 0 })
  expect(externalRequests).toEqual([])
  await page.evaluate(() => { window.dispatchEvent(new PageTransitionEvent('pagehide')); window.dispatchEvent(new PageTransitionEvent('pageshow', { persisted: true })) })
  await expect(page.getByRole('button', { name: 'Start with my own situation', exact: true })).toBeVisible()
  await page.route('https://www.wikipedia.org/**', route => route.fulfill({ contentType: 'text/html', body: '<h1>Neutral test destination</h1>' }))
  await page.getByRole('link', { name: 'Leave this page' }).click()
  await expect(page.getByRole('heading', { name: 'Neutral test destination' })).toBeVisible()
})

test('legacy walkthrough and help preserve the broader plan', async ({ page }) => {
  await personal(page)
  await page.getByRole('button', { name: /Look at devices using your Google account Google/ }).click()
  await page.getByRole('button', { name: 'I need the slower device walkthrough' }).click()
  await expect(page.getByRole('button', { name: 'Help me take the first step' })).toBeVisible()
  await page.getByRole('button', { name: 'Help me take the first step' }).click()
  await page.getByRole('button', { name: 'I don’t feel comfortable checking' }).click()
  await page.getByRole('button', { name: 'That’s enough for now' }).click()
  await page.getByRole('button', { name: 'Back to my plan', exact: true }).click()
  await expect(page.locator('#platform-heading')).toHaveText('Look at devices using your Google account')
  await page.getByRole('button', { name: 'Help & words', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Let’s make this easier to understand.' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to my plan', exact: true }).click()
  await expect(page.locator('#platform-heading')).toHaveText('Look at devices using your Google account')
  await page.getByRole('button', { name: 'Untangle home' }).click()
  await expect(page.locator('#platform-heading')).toHaveText('A little at a time is enough.')
  await expect(page.locator('.p-task-row')).toHaveCount(5)
})

test('explore supports adding preparation and private-image guidance without uploads', async ({ page }) => {
  await page.goto('/?view=plan')
  await nav(page, 'Explore guides').click()
  await page.getByRole('searchbox', { name: 'Search guides' }).fill('partner')
  await page.getByRole('button', { name: /Review Google Photos partner sharing/ }).click()
  await page.getByRole('button', { name: 'Add to my plan', exact: true }).click()
  await nav(page, 'My plan 2').click()
  await expect(page.locator('.p-next')).toContainText('Decide what you want to keep')
  await nav(page, 'Find support').click()
  await page.getByRole('button', { name: 'See private-image support' }).click()
  await expect(page.locator('.p-task-body')).toContainText('under 18 when an image was taken')
  await expect(page.locator('input[type=file]')).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Read StopNCII guidance/ })).toHaveAttribute('href', 'https://stopncii.org/how-it-works/')
})

test('responsive home, plan and guide pass accessibility checks', async ({ page }) => {
  test.setTimeout(120000)
  const audits: unknown[] = []
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/?view=plan')
    const startBox = await page.getByRole('button', { name: 'Make my own plan', exact: true }).boundingBox()
    expect(startBox!.y + startBox!.height).toBeLessThan(1000)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    audits.push({ width, page: 'home', violations: result.violations }); expect(result.violations).toEqual([])
    if (width === 390 || width === 1440) await capture(page, `home-${width}`)
    await page.getByRole('button', { name: width <= 1100 ? 'Explore an example plan' : 'Explore Maya’s example plan' }).click()
    await expect(page.locator('.p-example-banner')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 390 || width === 1440) await capture(page, `plan-${width}`)
    const planAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    audits.push({ width, page: 'plan', violations: planAudit.violations }); expect(planAudit.violations).toEqual([])
    await page.getByRole('button', { name: /Look at devices using your Google account Google/ }).click()
    await page.getByRole('button', { name: /Before a change/ }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 390 || width === 1440) await capture(page, `guide-${width}`)
    const guideAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    audits.push({ width, page: 'guide', violations: guideAudit.violations }); expect(guideAudit.violations).toEqual([])
  }
  fs.writeFileSync('docs/platform-accessibility-audit.json', JSON.stringify(audits, null, 2))
})
