import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import fs from 'node:fs'

const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64')
const imageFile = { name: 'private-reference.png', mimeType: 'image/png', buffer: png }
async function openDetailed(page: Page) {
  if (await page.locator('.advanced-start').getAttribute('open') === null) await page.locator('.advanced-start > summary').click()
}
async function openNote(page: Page) {
  await openDetailed(page)
  if (await page.locator('.optional-context').getAttribute('open') === null) await page.locator('.optional-context > summary').click()
}
async function toConnections(page: Page) {
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Show my summary' }).click()
}
async function shot(page: Page, name: string) {
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: `docs/screenshots/${name}.png`, fullPage: true, animations: 'disabled' })
}
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
}

test('shared tablet: complete flow, immutable previews, adviser summary and follow-up', async ({ page }) => {
  await page.goto('/?view=walkthrough')
  await shot(page, 'home')
  await openDetailed(page)
  await page.getByRole('button', { name: 'Show me an example' }).click()
  await expect(page.locator('#step-heading')).toBeFocused()
  await expect(page.locator('.mode-label .status-tag')).toContainText('Fictional example')
  await shot(page, 'desktop-review')
  await toConnections(page)
  await expect(page.locator('.plain-list').getByText('Main account is a recovery email for Backup account.', { exact: true })).toBeVisible()
  await page.locator('.connection-details > summary').click()
  await shot(page, 'desktop-connections')
  await page.getByRole('button', { name: 'See my options', exact: true }).click()
  await expect(page.getByText('Expected effect', { exact: true }).first()).toBeVisible()
  await shot(page, 'desktop-preview')
  await page.getByRole('button', { name: 'Changing a recovery email', exact: false }).click()
  await expect(page.getByText(/Google may still send codes to previous information for seven days/)).toBeVisible()
  await page.getByRole('button', { name: 'Signing out of the shared tablet', exact: false }).click()
  await expect(page.getByText(/Signing out this session does not change that setting/)).toBeVisible()
  await page.getByRole('button', { name: 'Make my next-step list' }).click()
  await expect(page.getByText('4 of 4 checks reviewed', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'The selected session now says signed out' }).click()
  await page.getByRole('button', { name: 'Add this update' }).click()
  await expect(page.locator('.log-item')).toContainText('Reported by you')
  await expect(page.locator('.followup-grid .check-list')).toContainText('Review the recovery email configured in Backup account.')
  await page.locator('.review-shell').getByText('Review together', { exact: false }).first().click()
  await expect(page.getByText('IN THIS TAB ONLY · NOTHING IS SENT')).toBeVisible()
  await shot(page, 'desktop-followup')
  await page.getByRole('button', { name: 'Your summary', exact: true }).click()
  await expect(page.getByText('Listed as signed in.', { exact: true })).toBeVisible()
})

test('distinct password and incomplete scenarios reset prior state', async ({ page }) => {
  await page.goto('/?view=walkthrough')
  await openDetailed(page)
  await page.getByRole('button', { name: 'Show me an example' }).click()
  await page.getByLabel('Choose fictional scenario').selectOption('password')
  await expect(page.getByText(/verification devices, some devices with third-party app access/)).toBeVisible()
  await toConnections(page)
  await page.getByRole('button', { name: 'See my options', exact: true }).click()
  await expect(page.getByText('We need more information', { exact: true })).toBeVisible()
  await page.getByLabel('Choose fictional scenario').selectOption('incomplete')
  await expect(page.locator('#step-heading')).toHaveText('Which Google account do you want to check?')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: 'Skip for now' }).click()
  await expect(page.getByText('The recovery-email relationship is not confirmed.')).toBeVisible()
  await page.getByRole('button', { name: 'See my options', exact: true }).click()
  await expect(page.getByText('We need more information', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Make my next-step list' }).click()
  await expect(page.getByText('0 of 4 checks reviewed')).toBeVisible()
})

test('manual review preserves answers on back; privacy network and memory boundaries', async ({ page }) => {
  const requests: string[] = []
  await page.route('**/*', async route => { requests.push(`${route.request().method()} ${route.request().url()} ${route.request().postData() || ''}`); await route.continue() })
  await page.goto('/?view=walkthrough')
  await openNote(page)
  await page.getByLabel('What would you like to review?').fill('PRIVATE-CONTEXT-458 location sharing and finances')
  await page.getByLabel('Add a settings screenshot').setInputFiles(imageFile)
  await expect(page.getByAltText('Your local settings image reference')).toBeVisible()
  await page.getByRole('button', { name: 'Start my review' }).click()
  await expect(page.getByText(/This prototype covers Google device sessions/)).toBeVisible()
  await page.getByRole('button', { name: /We used to share a device/  }).click()
  await page.getByRole('button', { name: /Possibly I’d like to understand/ }).click()
  await expect(page.getByText('You can just read and learn. You don’t have to change anything.')).toBeVisible()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Listed as signed in The selected entry says it is signed in', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Listed as signed in The selected entry says it is signed in', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(requests.filter(request => /PRIVATE-CONTEXT|private-reference|iVBORw0KGgo/.test(request))).toEqual([])
  expect(requests.filter(request => !request.includes('http://127.0.0.1:5173/'))).toEqual([])
  expect(await page.evaluate(() => [localStorage.length, sessionStorage.length])).toEqual([0, 0])
  expect(await page.evaluate(async () => (await indexedDB.databases()).length)).toBe(0)
  expect(await page.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).length)).toBe(0)
  await page.reload()
  await expect(page.getByLabel('What would you like to review?')).toHaveValue('')
  await expect(page.getByAltText('Your local settings image reference')).toHaveCount(0)
})

test('detailed review help gives context and returns to the same question without losing answers', async ({ page }) => {
  await page.goto('/?view=walkthrough')
  await openDetailed(page)
  await page.getByRole('button', { name: /I’m not sure where to start/ }).click()
  await page.getByRole('button', { name: 'Skip and continue →' }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.locator('.where-help > summary').click()
  await expect(page.locator('.where-help')).toContainText('Manage all devices')
  await page.getByRole('button', { name: 'Listed as signed in The selected entry says it is signed in', exact: true }).click()
  await page.getByRole('button', { name: 'I need an explanation' }).click()
  await expect(page.locator('#info-heading')).toBeFocused()
  await expect(page.locator('#step-heading')).not.toBeVisible()
  await page.getByText('Will clicking a button change my account?', { exact: false }).click()
  await expect(page.locator('.help-answer[open]')).toContainText('Any real account change happens separately in that service’s app or website.')
  const helpAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect(helpAudit.violations).toEqual([])
  await shot(page, 'desktop-help')
  await page.setViewportSize({ width: 320, height: 900 })
  await noOverflow(page)
  await page.setViewportSize({ width: 390, height: 900 })
  await shot(page, 'mobile-help')
  await page.getByRole('button', { name: 'Back to my check' }).click()
  await expect(page.locator('#step-heading')).toHaveText('Is the shared tablet still signed in?')
  await expect(page.getByRole('button', { name: 'Listed as signed in The selected entry says it is signed in', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.where-help')).toHaveAttribute('open', '')
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Show my summary' }).click()
  await page.getByRole('button', { name: 'See my options', exact: true }).click()
  await page.getByRole('button', { name: 'Make my next-step list' }).click()
  await page.getByRole('button', { name: 'Go back to my answers' }).click()
  await expect(page.getByRole('button', { name: /Next steps$/ })).toBeEnabled()
  await page.getByRole('button', { name: /Next steps$/ }).click()
  await expect(page.locator('#step-heading')).toHaveText('Here’s your list. Take it at your pace.')
})

test('empty text is allowed; clear confirmation does not block quick exit; back navigation resets', async ({ page }) => {
  await page.route('https://www.wikipedia.org/**', route => route.fulfill({ contentType: 'text/html', body: '<h1>Neutral destination</h1>' }))
  await page.goto('/?view=walkthrough')
  await openNote(page)
  await page.getByRole('button', { name: 'Start my review' }).click()
  await expect(page.locator('#step-heading')).toHaveText('What would you like help with?')
  await page.getByRole('button', { name: 'Clear this review' }).click()
  await page.getByRole('button', { name: 'Keep reviewing' }).click()
  await expect(page.locator('#step-heading')).toHaveText('What would you like help with?')
  await page.getByRole('button', { name: 'Clear this review' }).click()
  await page.getByRole('button', { name: 'Yes, clear review' }).click()
  await openNote(page)
  await page.getByLabel('What would you like to review?').fill('sensitive exit context')
  await page.getByRole('button', { name: 'Start my review' }).click()
  await page.getByRole('button', { name: 'Clear this review' }).click()
  await page.getByRole('link', { name: 'Leave this page' }).click()
  await expect(page).toHaveURL('https://www.wikipedia.org/')
  await expect(page.getByRole('heading')).toHaveText('Neutral destination')
  await page.goBack()
  await expect(page.getByText('sensitive exit context')).toHaveCount(0)
  await page.goto('/?view=walkthrough')
  await expect(page.getByLabel('What would you like to review?')).toHaveValue('')
})

test('restored page clears in-memory text and revokes image references', async ({ page }) => {
  await page.addInitScript(() => {
    const original = URL.revokeObjectURL.bind(URL)
    const revoked: string[] = []
    Object.assign(window, { revoked })
    URL.revokeObjectURL = url => { revoked.push(url); original(url) }
  })
  await page.goto('/?view=walkthrough')
  await openNote(page)
  await page.getByLabel('What would you like to review?').fill('bfcache-private')
  await page.getByLabel('Add a settings screenshot').setInputFiles(imageFile)
  await expect(page.getByAltText('Your local settings image reference')).toBeVisible()
  await page.getByRole('button', { name: 'Start my review' }).click()
  await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pagehide', { persisted: true })))
  await expect(page.locator('#root')).toHaveCSS('visibility', 'hidden')
  await page.evaluate(() => window.dispatchEvent(new PageTransitionEvent('pageshow', { persisted: true })))
  await expect(page.getByLabel('What would you like to review?')).toHaveValue('')
  await expect(page.getByAltText('Your local settings image reference')).toHaveCount(0)
  expect(await page.evaluate(() => (window as unknown as { revoked: string[] }).revoked.length)).toBeGreaterThan(0)
})

test('image picker errors, remove, replace and drag-drop share validation', async ({ page }) => {
  await page.goto('/?view=walkthrough')
  await openNote(page)
  const picker = page.getByLabel('Add a settings screenshot')
  await picker.setInputFiles({ name: 'not-image.txt', mimeType: 'text/plain', buffer: Buffer.from('not an image') })
  await expect(page.getByRole('alert')).toContainText('Use a PNG, JPEG or WebP')
  await picker.setInputFiles({ name: 'large.png', mimeType: 'image/png', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) })
  await expect(page.getByRole('alert')).toContainText('larger than 10 MB')
  await picker.setInputFiles({ name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('broken bytes') })
  await expect(page.getByRole('alert')).toContainText('could not be read')
  const huge = Buffer.from(png); huge.writeUInt32BE(100_000, 16)
  await picker.setInputFiles({ name: 'huge.png', mimeType: 'image/png', buffer: huge })
  await expect(page.getByRole('alert')).toContainText('too large to display')
  await picker.setInputFiles([])
  await expect(page.getByAltText('Your local settings image reference')).toHaveCount(0)
  await page.locator('.dropzone').evaluate((el, bytes) => {
    const dt = new DataTransfer()
    for (let i = 0; i < 2; i++) dt.items.add(new File([new Uint8Array(bytes)], 'image.png', { type: 'image/png' }))
    el.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: dt }))
  }, [...png])
  await expect(page.getByRole('alert')).toContainText('one image at a time')
  await page.locator('.dropzone').evaluate((el, bytes) => {
    const dt = new DataTransfer(); dt.items.add(new File([new Uint8Array(bytes)], 'image.png', { type: 'image/png' }))
    el.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: dt }))
  }, [...png])
  await expect(page.getByAltText('Your local settings image reference')).toBeVisible()
  const originalUrl = await page.getByAltText('Your local settings image reference').getAttribute('src')
  await page.getByLabel('Replace image reference').setInputFiles(imageFile)
  await expect(page.getByAltText('Your local settings image reference')).not.toHaveAttribute('src', originalUrl!)
  expect(await page.evaluate(async url => { try { await fetch(url!); return true } catch { return false } }, originalUrl)).toBe(false)
  await page.getByRole('button', { name: 'Remove image' }).click()
  await expect(page.getByAltText('Your local settings image reference')).toHaveCount(0)
  await picker.setInputFiles(imageFile)
  await expect(page.getByAltText('Your local settings image reference')).toBeVisible()
  await openDetailed(page)
  await page.getByRole('button', { name: 'Show me an example' }).click()
  await expect(page.getByAltText('Your local settings image reference')).toHaveCount(0)
})

test('responsive flow at 320, 390, 768, 1440 and 200% zoom-equivalent viewport', async ({ page }) => {
  test.setTimeout(60000)
  for (const width of [320, 390, 768, 1440, 720]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/?view=walkthrough')
    await noOverflow(page)
    if (width === 390) await shot(page, 'home-mobile')
    await openDetailed(page)
  await page.getByRole('button', { name: 'Show me an example' }).click()
    await noOverflow(page)
    if (width === 390) await shot(page, 'mobile-review')
    await toConnections(page)
    await noOverflow(page)
    await page.locator('.connection-details > summary').click()
    await noOverflow(page)
    if (width === 390) await shot(page, 'mobile-connections')
    await page.getByRole('button', { name: 'See my options', exact: true }).click()
    await noOverflow(page)
    if (width === 390) await shot(page, 'mobile-preview')
    await page.getByRole('button', { name: 'Make my next-step list' }).click()
    await noOverflow(page)
    if (width === 390) await shot(page, 'mobile-followup')
  }
})

test('keyboard, reduced motion, contrast and automated accessibility', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?view=walkthrough')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Untangle home' })).toBeFocused()
  await openDetailed(page)
  await page.getByRole('button', { name: 'Show me an example' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#step-heading')).toBeFocused()
  expect(await page.locator('.step-content').evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  const reviewAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect(reviewAudit.violations).toEqual([])
  await toConnections(page)
  const connectionsAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect(connectionsAudit.violations).toEqual([])
  await page.getByRole('button', { name: 'See my options', exact: true }).click()
  const previewAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect(previewAudit.violations).toEqual([])
  await page.getByRole('button', { name: 'Make my next-step list' }).click()
  const followupAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect(followupAudit.violations).toEqual([])
  await page.goto('/?view=walkthrough')
  const homeAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect(homeAudit.violations).toEqual([])
  fs.writeFileSync('docs/accessibility-audit.json', JSON.stringify({ checked: '2026-10-03', engine: 'axe-core', pages: ['home', 'review', 'connections', 'preview', 'followup'], violations: 0 }, null, 2))
})
