import { useTranslation } from '../../i18n/context'
import type { Dispatch } from 'react'
import { ArrowLeft, ArrowRight, ChevronDown, CircleHelp, ListChecks, Mail, Monitor } from 'lucide-react'
import { Button } from '../../components/Primitives'
import type { Action, State } from '../../app/state'
import { nextChecks, otherAccount, PASSWORD_EXCEPTIONS, recoverySentence, relationships, sessionLabels } from '../../domain/rules'

export function Connections({ state, dispatch }: { state: State; dispatch: Dispatch<Action> }) {
  const { translate } = useTranslation()

  const o = state.observations
  const edges = relationships(o, state.mode)
  return <section>
    <div className="section-heading"><span className="section-label">{translate("YOUR SUMMARY")}</span><h1 id="step-heading" tabIndex={-1}>{translate("Here’s what you told us.")}</h1><p className="step-description">{translate("These are ")}{translate(state.mode === 'example' ? 'the details from your made-up example' : 'your answers')}{translate(". Untangle hasn’t checked your accounts. You can go back and change an answer.")}</p></div>
    <div className="summary-grid plain-list">
      <article className="app-card summary-card"><div className="card-heading"><span className="icon-tile peach"><Monitor size={24} aria-hidden="true" /></span><div><span className="section-label">{translate("THE DEVICE")}</span><h2>{translate("Shared tablet")}</h2></div><span className="status-tag">{translate(state.mode === 'example' ? 'Example data' : 'Your answer')}</span></div><div className="answer-line"><strong>{translate(o.account)}</strong><span>{translate(sessionLabels[o.session])}.</span></div><p>{translate(o.session === 'signed-in' ? 'You said this account is still signed in on the selected tablet entry.' : o.session === 'signed-out' ? 'You said the selected tablet entry shows “Signed out”. This only tells us about that entry.' : o.session === 'not-shown' ? 'You couldn’t find the tablet. That alone doesn’t prove every sign-in has ended.' : 'You haven’t confirmed whether this tablet is signed in. That stays on your list.')}</p><div className="summary-context"><strong>{translate("Do you still use it?")}</strong><span>{translate(o.control === 'yes' ? 'You said yes.' : o.control === 'no' ? 'You said no.' : 'You’re not sure yet.')}</span></div></article>
      <article className="app-card summary-card"><div className="card-heading"><span className="icon-tile lavender"><Mail size={24} aria-hidden="true" /></span><div><span className="section-label">{translate("THE EMAIL LINK")}</span><h2>{translate("Your two accounts")}</h2></div></div><div className="answer-line"><strong>{translate(o.recovery === 'present' ? 'A link was reported' : o.recovery === 'absent' ? 'No link was reported' : 'Still needs checking')}</strong><span>{translate(o.recovery === 'present' ? recoverySentence(o) : o.recovery === 'absent' ? `You said ${otherAccount(o.account)} does not use ${o.account} as its recovery email, or you don’t have a second account.` : 'The recovery-email relationship is not confirmed.')}</span></div><p>{translate(o.recovery === 'present' ? `That means Google may use ${o.account} to help someone get back into ${otherAccount(o.account)}. Other checks may still be needed.` : 'A recovery email is an email Google may use to help you get back into another account.')}</p><div className="summary-context"><CircleHelp size={16} aria-hidden="true" /><span>{translate("This doesn’t prove anyone has accessed the other account.")}</span></div></article>
    </div>
    <div className="summary-bottom-grid">
      <section className="meaning-card"><h2>{translate("What does this mean for me?")}</h2><p>{translate(o.session === 'signed-in' && o.recovery === 'present' ? 'The tablet sign-in and the email link are two separate things to look at. Changing one may leave the other in place.' : 'You have a starting point. Details you aren’t sure about can stay on your list until you’re ready to check.')}</p><p>{translate("A sign-in listing doesn’t tell us who used the device. An email link doesn’t automatically give someone access.")}</p>{o.passwordChanged && <p className="tinted-note">{translate(PASSWORD_EXCEPTIONS)}</p>}</section>
      <section className="app-card next-checks"><div className="card-heading"><ListChecks size={21} aria-hidden="true" /><h2>{translate("Things to look at next")}</h2></div><ul className="check-list">{nextChecks(o).map(item => <li key={item}><span aria-hidden="true">○</span>{translate(item)}</li>)}</ul>{!nextChecks(o).length && <p>{translate("You reviewed these questions. That does not prove all account access has ended.")}</p>}</section>
    </div>
    <details className="connection-details app-card"><summary>{translate("Show connections ")}<span>{translate("A simple picture of these details")}</span><ChevronDown size={18} aria-hidden="true" /></summary><div className="diagram-wrap"><svg viewBox="0 0 880 140" className="connection-svg" role="img" aria-label={translate("The tablet connects to the selected account. That account can be a recovery email for the other account. Read the list below for the status of each link.")}><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="none" stroke="currentColor" /></marker></defs><path d="M210 75H312" stroke="currentColor" strokeWidth="1.5" strokeDasharray="5 5" markerEnd="url(#arrow)" fill="none" /><path d="M555 75H650" stroke="currentColor" strokeWidth="1.5" strokeDasharray="5 5" markerEnd="url(#arrow)" fill="none" /><g><rect x="5" y="45" width="205" height="60" rx="10" /><text x="108" y="81">{translate("Shared tablet")}</text></g><g><rect x="320" y="45" width="235" height="60" rx="10" /><text x="437" y="81">{translate(o.account)}</text></g><g><rect x="657" y="45" width="218" height="60" rx="10" /><text x="766" y="81">{translate(otherAccount(o.account))}</text></g><text x="265" y="31" className="edge-label">{translate(o.session === 'signed-in' ? 'Listed sign-in' : 'No confirmed active sign-in')}</text><text x="606" y="124" className="edge-label">{translate(o.recovery === 'present' ? 'Recovery email for' : 'No confirmed email link')}</text></svg><ul className="relationship-list"><li>{translate("Shared tablet ")}<ArrowRight size={15} aria-hidden="true" /> {translate(o.account)}: {translate(sessionLabels[o.session])}.</li><li>{translate(o.recovery === 'present' ? recoverySentence(o) : `Whether ${o.account} is a recovery email for ${otherAccount(o.account)}: ${o.recovery === 'absent' ? 'reported absent' : 'unknown'}.`)}</li></ul><p className="small-print">{translate(`Connections reported in your answers: ${edges.length}. The lines show possible relationships, not verified access.`)}</p></div></details>
    <div className="next-explanation"><strong>{translate("Next: understand your options")}</strong><p>{translate("See what signing out or changing a recovery email could do. Nothing will be changed.")}</p></div><div className="step-actions"><button className="text-button" onClick={() => { dispatch({ type: 'QUESTION', value: 0 }); dispatch({ type: 'STEP', value: 'review' }) }}><ArrowLeft size={16} aria-hidden="true" />{translate("Edit my answers")}</button><Button arrow onClick={() => dispatch({ type: 'STEP', value: 'preview' })}>{translate("See my options")}</Button></div>
  </section>
}
