import type { Dispatch } from 'react'
import { ArrowLeft, ArrowRight, ChevronDown, CircleHelp, ListChecks, Mail, Monitor } from 'lucide-react'
import { Button } from '../../components/Primitives'
import type { Action, State } from '../../app/state'
import { nextChecks, otherAccount, PASSWORD_EXCEPTIONS, recoverySentence, relationships, sessionLabels } from '../../domain/rules'

export function Connections({ state, dispatch }: { state: State; dispatch: Dispatch<Action> }) {
  const o = state.observations
  const edges = relationships(o, state.mode)
  return <section>
    <div className="section-heading"><span className="section-label">YOUR SUMMARY</span><h1 id="step-heading" tabIndex={-1}>Here’s what you told us.</h1><p className="step-description">These are {state.mode === 'example' ? 'the details from your made-up example' : 'your answers'}. Untangle hasn’t checked your accounts. You can go back and change an answer.</p></div>
    <div className="summary-grid plain-list">
      <article className="app-card summary-card"><div className="card-heading"><span className="icon-tile peach"><Monitor size={24} aria-hidden="true" /></span><div><span className="section-label">THE DEVICE</span><h2>Shared tablet</h2></div><span className="status-tag">{state.mode === 'example' ? 'Example data' : 'Your answer'}</span></div><div className="answer-line"><strong>{o.account}</strong><span>{sessionLabels[o.session]}.</span></div><p>{o.session === 'signed-in' ? 'You said this account is still signed in on the selected tablet entry.' : o.session === 'signed-out' ? 'You said the selected tablet entry shows “Signed out”. This only tells us about that entry.' : o.session === 'not-shown' ? 'You couldn’t find the tablet. That alone doesn’t prove every sign-in has ended.' : 'You haven’t confirmed whether this tablet is signed in. That stays on your list.'}</p><div className="summary-context"><strong>Do you still use it?</strong><span>{o.control === 'yes' ? 'You said yes.' : o.control === 'no' ? 'You said no.' : 'You’re not sure yet.'}</span></div></article>
      <article className="app-card summary-card"><div className="card-heading"><span className="icon-tile lavender"><Mail size={24} aria-hidden="true" /></span><div><span className="section-label">THE EMAIL LINK</span><h2>Your two accounts</h2></div></div><div className="answer-line"><strong>{o.recovery === 'present' ? 'A link was reported' : o.recovery === 'absent' ? 'No link was reported' : 'Still needs checking'}</strong><span>{o.recovery === 'present' ? recoverySentence(o) : o.recovery === 'absent' ? `You said ${otherAccount(o.account)} does not use ${o.account} as its recovery email, or you don’t have a second account.` : 'The recovery-email relationship is not confirmed.'}</span></div><p>{o.recovery === 'present' ? `That means Google may use ${o.account} to help someone get back into ${otherAccount(o.account)}. Other checks may still be needed.` : 'A recovery email is an email Google may use to help you get back into another account.'}</p><div className="summary-context"><CircleHelp size={16} aria-hidden="true" /><span>This doesn’t prove anyone has accessed the other account.</span></div></article>
    </div>
    <div className="summary-bottom-grid">
      <section className="meaning-card"><h2>What does this mean for me?</h2><p>{o.session === 'signed-in' && o.recovery === 'present' ? 'The tablet sign-in and the email link are two separate things to look at. Changing one may leave the other in place.' : 'You have a starting point. Details you aren’t sure about can stay on your list until you’re ready to check.'}</p><p>A sign-in listing doesn’t tell us who used the device. An email link doesn’t automatically give someone access.</p>{o.passwordChanged && <p className="tinted-note">{PASSWORD_EXCEPTIONS}</p>}</section>
      <section className="app-card next-checks"><div className="card-heading"><ListChecks size={21} aria-hidden="true" /><h2>Things to look at next</h2></div><ul className="check-list">{nextChecks(o).map(item => <li key={item}><span aria-hidden="true">○</span>{item}</li>)}</ul>{!nextChecks(o).length && <p>You reviewed these questions. That does not prove all account access has ended.</p>}</section>
    </div>
    <details className="connection-details app-card"><summary>Show connections <span>A simple picture of these details</span><ChevronDown size={18} aria-hidden="true" /></summary><div className="diagram-wrap"><svg viewBox="0 0 880 140" className="connection-svg" role="img" aria-label="The tablet connects to the selected account. That account can be a recovery email for the other account. Read the list below for the status of each link."><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="none" stroke="currentColor" /></marker></defs><path d="M210 75H312" stroke="currentColor" strokeWidth="1.5" strokeDasharray="5 5" markerEnd="url(#arrow)" fill="none" /><path d="M555 75H650" stroke="currentColor" strokeWidth="1.5" strokeDasharray="5 5" markerEnd="url(#arrow)" fill="none" /><g><rect x="5" y="45" width="205" height="60" rx="10" /><text x="108" y="81">Shared tablet</text></g><g><rect x="320" y="45" width="235" height="60" rx="10" /><text x="437" y="81">{o.account}</text></g><g><rect x="657" y="45" width="218" height="60" rx="10" /><text x="766" y="81">{otherAccount(o.account)}</text></g><text x="265" y="31" className="edge-label">{o.session === 'signed-in' ? 'Listed sign-in' : 'No confirmed active sign-in'}</text><text x="606" y="124" className="edge-label">{o.recovery === 'present' ? 'Recovery email for' : 'No confirmed email link'}</text></svg><ul className="relationship-list"><li>Shared tablet <ArrowRight size={15} aria-hidden="true" /> {o.account}: {sessionLabels[o.session]}.</li><li>{o.recovery === 'present' ? recoverySentence(o) : `Whether ${o.account} is a recovery email for ${otherAccount(o.account)}: ${o.recovery === 'absent' ? 'reported absent' : 'unknown'}.`}</li></ul><p className="small-print">{edges.length} connection{edges.length === 1 ? '' : 's'} reported in your answers. The lines show possible relationships, not verified access.</p></div></details>
    <div className="next-explanation"><strong>Next: understand your options</strong><p>See what signing out or changing a recovery email could do. Nothing will be changed.</p></div><div className="step-actions"><button className="text-button" onClick={() => { dispatch({ type: 'QUESTION', value: 0 }); dispatch({ type: 'STEP', value: 'review' }) }}><ArrowLeft size={16} aria-hidden="true" />Edit my answers</button><Button arrow onClick={() => dispatch({ type: 'STEP', value: 'preview' })}>See my options</Button></div>
  </section>
}
