export const concerns = [
  { id: 'accounts', title: 'Who can get into my accounts?', short: 'Accounts & messages', detail: 'Email, passwords and devices you used together.', icon: 'key' },
  { id: 'location', title: 'Can someone see where I am?', short: 'Location sharing', detail: 'Location shared through your phone or apps.', icon: 'pin' },
  { id: 'photos', title: 'What happens to our photos?', short: 'Photos & memories', detail: 'Shared albums, saved copies and private images.', icon: 'image' },
  { id: 'messages', title: 'I want to keep important messages.', short: 'Messages to keep', detail: 'Think about what to keep before deleting or blocking.', icon: 'message' },
  { id: 'shared', title: 'We still share everyday things.', short: 'Shared everyday life', detail: 'Family plans, subscriptions and home devices.', icon: 'home' },
  { id: 'support', title: 'I would like someone to help.', short: 'Someone alongside me', detail: 'Find support or prepare to talk to someone you trust.', icon: 'heart' },
] as const
export type ConcernId = typeof concerns[number]['id']
export type TaskId = 'recovery' | 'devices' | 'password' | 'forwarding' | 'maps' | 'apple' | 'keep' | 'photos' | 'whatsapp' | 'family' | 'home' | 'images' | 'support'
export interface Task {
  id: TaskId; title: string; category: ConcernId; service: string; minutes: string; intro: string; steps: string[];
  impact: string; boundary: string; reported: string; prerequisites: TaskId[]; source: string; url: string; action?: { label: string; url: string };
}
export const tasks: Task[] = [
  { id: 'recovery', title: 'Keep a way back into your account', category: 'accounts', service: 'Google · Gmail', minutes: '3–5 min', intro: 'A recovery email or phone helps you get back in if you forget your password. Start by finding out whether you can use yours.', steps: ['Open Google’s recovery guide. Look for your recovery phone and email in your account settings.', 'Can you still receive messages at those places? Does anyone else use them? You don’t need to enter the details here.'], impact: 'Before changing a password or removing access, consider how you would sign in again. If someone else controls that phone or email, ask for help making a plan.', boundary: 'Google may still offer the previous recovery details for 7 days after a change. This check does not prove that only you can access the account.', reported: 'I checked how I would get back in', prerequisites: [], source: 'Google: recovery phone and email', url: 'https://support.google.com/accounts/answer/183723?hl=en' },
  { id: 'devices', title: 'Look at devices using your Google account', category: 'accounts', service: 'Google · Gmail', minutes: '3–5 min', intro: 'A laptop or phone you used together might still have a signed-in account. Google lists current and recent connections.', steps: ['Open your Google device list. Make sure you are looking at your own account.', 'Choose an entry you recognise. Read whether it says “Signed out”. If the names are confusing, leave the result as “I’m not sure”.'], impact: 'Signing out an entry can end that connection. Google can list several sessions for one device, so one sign-out may not cover them all. The person using it may notice.', boundary: 'A device name or recent time does not tell you who used it. Signing out does not remove copies of files already saved.', reported: 'I checked the entries I wanted to review', prerequisites: ['recovery'], source: 'Google: devices with account access', url: 'https://support.google.com/accounts/answer/3067630?hl=en', action: { label: 'Open my Google device list', url: 'https://www.google.com/devices' } },
  { id: 'password', title: 'Understand what changing a password does', category: 'accounts', service: 'Google · Gmail', minutes: '2–3 min', intro: 'A new password can help when an old one was shared. It is only one part of separating accounts.', steps: ['First check that you can use your recovery email or phone.', 'Read Google’s password guide before deciding whether to change it. Use a password you do not use elsewhere; never type it into this guide.'], impact: 'A Google password change signs you out in many places, with exceptions including some identity-verification devices and some connected apps or home devices.', boundary: 'A password change alone does not review your location sharing, email forwarding or saved photo copies. Keep those checks in your plan if they apply.', reported: 'I understand the change and checked my next step', prerequisites: ['recovery'], source: 'Google: change or reset a password', url: 'https://support.google.com/accounts/answer/41078?hl=en' },
  { id: 'forwarding', title: 'Check whether your emails go somewhere else', category: 'accounts', service: 'Gmail · computer', minutes: '3–5 min', intro: 'Gmail can send incoming messages to another email address automatically. This is called forwarding.', steps: ['On a computer, open Gmail → Settings → See all settings → Forwarding (or Forwarding and POP/IMAP). Read whether forwarding is on.', 'Check the filters in your Gmail settings too: individual filters can forward selected messages. If you cannot tell, keep this as a question for support.'], impact: 'Turning off forwarding stops that route for future messages. Individual forwarding filters need a separate review.', boundary: 'Messages already delivered elsewhere are not recalled. A password change does not replace checking forwarding.', reported: 'I checked forwarding and forwarding filters', prerequisites: ['recovery'], source: 'Google: automatic forwarding', url: 'https://support.google.com/mail/answer/10957?hl=en' },
  { id: 'maps', title: 'See who can view your location in Google Maps', category: 'location', service: 'Google Maps', minutes: '2–4 min', intro: 'Location sharing lets selected people see where you are. It can stay on even when Timeline is off.', steps: ['Open Google Maps. Look for Location sharing in your profile menu (or the menu on a computer).', 'Look at who appears in the sharing list. You can read the list without deciding to stop sharing yet.'], impact: 'Stopping sharing with a person ends that Google Maps sharing relationship. They may notice your location is no longer available.', boundary: 'This does not check other apps, family services, physical trackers or someone else’s account on your phone.', reported: 'I checked my Google Maps sharing list', prerequisites: [], source: 'Google Maps: Location Sharing', url: 'https://support.google.com/maps/answer/15437054?hl=en' },
  { id: 'apple', title: 'Review sharing on your iPhone', category: 'location', service: 'iPhone · iOS 16 or later', minutes: '5–10 min', intro: 'Apple’s Safety Check brings several Apple sharing settings together. You choose what to review.', steps: ['On your iPhone, open Settings → Privacy & Security → Safety Check.', 'Read about “Manage Sharing & Access” in Apple’s guide. It lets you review people, apps and account access. Read before confirming changes.'], impact: 'Changing sharing can affect people and apps using that information. Others may notice the change. You can pause and ask for support.', boundary: 'Apple’s tool does not cover every social app or non-Apple account. Availability and screens depend on your iPhone and settings.', reported: 'I reviewed the Apple sharing settings relevant to me', prerequisites: [], source: 'Apple: Safety Check', url: 'https://support.apple.com/en-euro/guide/personal-safety/ips1c3310dd2/web' },
  { id: 'keep', title: 'Decide what you want to keep', category: 'messages', service: 'Photos · messages · files', minutes: 'At your pace', intro: 'Before deleting messages or leaving a shared space, think about anything you may want later. You can make this decision with someone you trust.', steps: ['Think about important messages, memories or documents. You do not need to upload them or describe them here.', 'Consider where a copy could be kept without someone else getting access. If making a copy could cause problems, pause and discuss it with support.'], impact: 'Deleting, reporting or losing shared access can make some information harder to retrieve. There is no need to delete anything to complete this guide.', boundary: 'Untangle is not an evidence store. It cannot check a device for monitoring or establish whether a record meets legal requirements.', reported: 'I have considered what to keep and where', prerequisites: [], source: 'Safety Net: documentation tips', url: 'https://www.techsafety.org/documentationtips' },
  { id: 'photos', title: 'Review Google Photos partner sharing', category: 'photos', service: 'Google Photos', minutes: '3–5 min', intro: 'Partner sharing can automatically share photos with one person. Stopping it and deleting saved copies are different things.', steps: ['On a computer, open Google Photos → Settings → Sharing → Partner sharing.', 'Read what is shared and with whom. Think about photos you want to keep before deciding to remove a partner.'], impact: 'Removing a partner stops partner sharing. Photos already saved to either person’s account remain there.', boundary: 'This does not remove screenshots, downloads or other shared albums. It cannot make another person delete a copy.', reported: 'I checked partner sharing and understand saved copies', prerequisites: ['keep'], source: 'Google Photos: partner sharing', url: 'https://support.google.com/photos/answer/7378858?hl=en' },
  { id: 'whatsapp', title: 'Review devices linked to WhatsApp', category: 'accounts', service: 'WhatsApp', minutes: '3–5 min', intro: 'WhatsApp can also work on linked computers and other devices. Those connections deserve their own check.', steps: ['Open WhatsApp’s official guide below to find Linked devices on your phone.', 'Review the devices listed. If you cannot recognise an entry, you can keep it as an open question before deciding to unlink it.'], impact: 'Unlinking a device ends that WhatsApp connection. The person using that device may notice.', boundary: 'This does not delete screenshots or messages already copied elsewhere. Untangle cannot inspect your linked devices.', reported: 'I checked my WhatsApp linked-device list', prerequisites: [], source: 'WhatsApp: review linked devices', url: 'https://faq.whatsapp.com/1428782138011916/?cms_platform=web' },
  { id: 'family', title: 'Plan around a shared Apple family group', category: 'shared', service: 'Apple Family Sharing', minutes: '5–10 min', intro: 'A family group may connect subscriptions, purchases and storage. Find out what you rely on before leaving.', steps: ['Open Settings → Family (or your name → Family, depending on your device). Look at the group and shared services.', 'Note anything you need to keep using. Read Apple’s guide for your role, age and region before making changes.'], impact: 'Leaving can immediately remove access to other people’s shared purchases and services. An organiser ending the group affects everyone.', boundary: 'Shared iCloud storage alone does not let members read each other’s private files. Child and teen account options vary by age and region.', reported: 'I checked what I would lose or need to replace', prerequisites: ['keep'], source: 'Apple: manage Family Sharing', url: 'https://support.apple.com/en-euro/guide/personal-safety/ips75b3b794f/1.0/web/1.0' },
  { id: 'home', title: 'Think through shared home devices', category: 'shared', service: 'Cameras · speakers · Wi-Fi', minutes: 'With support', intro: 'Home devices may belong to a shared account or be controlled by someone else. Start with what you know, without resetting anything.', steps: ['Think of connected items you use: a doorbell, camera, speaker or router. You don’t need to search for devices alone.', 'Use Refuge’s device-specific guides, or take this question to someone who can help you review ownership and access.'], impact: 'Removing an account or resetting a device can interrupt everyday services and alert someone who uses them. Consider the practical effects first.', boundary: 'Untangle cannot detect hidden devices, spyware or tracking. A short checklist cannot rule them out.', reported: 'I reviewed the devices I know about and my next step', prerequisites: [], source: 'Refuge: tech safety guides', url: 'https://refugetechsafety.org/' },
  { id: 'images', title: 'Get help with private images', category: 'photos', service: 'Specialist support', minutes: 'At your pace', intro: 'If someone has shared, or threatened to share, intimate images, specialist services may be able to help. You do not need to show Untangle any images.', steps: ['If you were under 18 when an image was taken, visit NCMEC’s Take It Down to read about your options—even if you are older now.', 'For adult images, visit StopNCII and check its eligibility. Both tools create a digital fingerprint on your device; they do not need the image uploaded to them.'], impact: 'These services work with participating platforms. They cannot guarantee removal from every website or private conversation.', boundary: 'Do not download or ask anyone to send an image just to use Take It Down. Use its guidance for images already on your device.', reported: 'I found the specialist guidance I need', prerequisites: [], source: 'NCMEC: Take It Down', url: 'https://takeitdown.ncmec.org/', action: { label: 'Read StopNCII guidance', url: 'https://stopncii.org/how-it-works/' } },
  { id: 'support', title: 'Choose someone to work through this with', category: 'support', service: 'A trusted person · specialist support', minutes: 'At your pace', intro: 'You can ask for help with one small thing. You do not have to explain the whole relationship to use this plan.', steps: ['Think of a person or support service you would feel comfortable speaking with. For a young person, this could be a trusted adult or youth support service.', 'Open “Review together” to see your questions in one place. You decide what to show; Untangle does not send it to anyone.'], impact: 'Tell the person what help you want and ask them to check with you before changing settings.', boundary: 'There is no live adviser in Untangle. Lila.help can help you look for services in your region.', reported: 'I know whom I would like to ask', prerequisites: [], source: 'Lila.help: find support', url: 'https://lila.help/' },
]
export const taskById = Object.fromEntries(tasks.map(t => [t.id, t])) as Record<TaskId, Task>
export const defaultTasks: Record<ConcernId, TaskId[]> = {
  accounts: ['recovery', 'devices', 'forwarding', 'whatsapp', 'password'], location: ['maps', 'apple'], photos: ['keep', 'photos'], messages: ['keep'], shared: ['keep', 'family', 'home'], support: ['support'],
}
